name: Snyk Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '28 16 * * 3'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Installing dependencies
        run: npm install
        
      - name: Synk CLI setup
        uses: snyk/actions/setup@master
        
      - name: Running Synk
        shell: bash
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: | 
              --sarif-file-output=snyk.sarif 
   
      - name: Debug of sarif file
        run: | 
            if [ -f "snyk.sarif" ]; then
              echo "snyk.sarif exists."
            else
              echo "snyk.sarif NOT FOUND. Snyk might have failed to detect your project."
              exit 1
            fi        
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
